### ISSUE TITLE
Various networking issues

### ISSUE THREAD

**Issue by lpinca** [alexhultman/uWebSockets#82] opened 2016-04-29 06:32 UTC
Follow up of #71.

I tried removing this line

```js
server.send(socket, message, binary);
```

from the example posted [here](https://github.com/alexhultman/uWebSockets/issues/71#issuecomment-215445418) and with this change all messages are received on the server.

Then I tried to reverse the order of messages, sending data from server to client:

```js
'use strict';

const WebSocket = require('faye-websocket');
const crypto = require('crypto');
const uws = require('uws');

const messages = [];
let i = 10000;

while (i--) {
  const size = Math.floor(Math.random() * 1000) + 1;
  messages.push(crypto.randomBytes(size));
}

const server = new uws.uws.Server(8080);

server.onConnection(socket => {
  messages.forEach(message => server.send(socket, message, true));
});

const socket = new WebSocket.Client('ws://localhost:8080');

socket.on('message', () => console.log(++i));
socket.on('error', err => console.error(err));
socket.on('close', () => console.log('close'));
```

The above example closes the client with an error:

```
Received unexpected continuation frame
```

The same happens if `ws` is used as client.

I wasn't able to reproduce the error on Linux.

**Comment by alexhultman** [comment] 2016-04-29 08:37
I'm currently working on the SSL support, I think I'm very close to having the full Autobahn pass. Then I'll merge things in and fix a few obvious networking errors I found. Also, the socket -> p change is fixing a very broken path in the parser so this will need to be puched before we can test other bugs I think.

**Comment by lpinca** [comment] 2016-04-29 08:42
I already tried the `socket -> p` change but it doesn't seem to fix this issue.
Anyway take you time, there is no hurry!

**Comment by alexhultman** [comment] 2016-04-30 08:29
I get another error, one about reserved bits on. I should probably start to perform some more testing on OS X. Like you say, this is OS X only.

**Comment by alexhultman** [comment] 2016-05-03 12:21
Well good news is I finally managed to reproduce it on Linux. It seems to happen only when setting the send buffer to very small, I guess OS X has a smaller buffer set by default.

**Comment by lpinca** [comment] 2016-05-03 16:34
It still doesn't work as expected, I tried this on OS X:
```js
'use strict';

const WebSocket = require('faye-websocket');
const crypto = require('crypto');
const uws = require('uws');

const messages = [];
let i = 10000;

while (i--) {
  const size = Math.floor(Math.random() * 1000) + 1;
  messages.push(crypto.randomBytes(size));
}

const server = new uws.uws.Server(8080);

server.onMessage((socket, message, binary) => {
  console.log(++i);
  server.send(socket, message, binary);
});

const socket = new WebSocket.Client('ws://localhost:8080');

socket.on('open', () => messages.forEach(message => socket.send(message)));
socket.on('error', err => console.error(err));
socket.on('close', () => console.log('close'));
```

`onMessage` is not invoked the expected amount of times. If `server.send(socket, message, binary);` is removed the count is correct.

**Comment by lpinca** [comment] 2016-05-03 16:36
Client is not closed and no error is emitted.

**Comment by alexhultman** [comment] 2016-05-03 19:15
Yeah you're right, there are still some issues left but we are solving a lot of central issues one by one. I guess we'll reach a somewhat stable release in the upcoming minor releases.

**Comment by alexhultman** [comment] 2016-05-03 21:39
This should be fixed now. Seems to be some kind of deadlock where the system never let me write anymore before reading what was in the buffer. Now I always handle reads, even if I have a bunch of writes to complete.

You know how to compile this right?

make clean
make targets
make

**Comment by alexhultman** [comment] 2016-05-03 21:51
Never mind I pushed a new release on NPM.

**Closed** 2016-05-03 22:00 UTC
Labels: bug, high priority

**Comment by lpinca** [comment] 2016-05-04 06:41
Yes I compiled it before (I struggled a bit with OpenSSL dependency on OS X).
Anyway it works now and I have no new issues to report, for now :)

**Comment by alexhultman** [comment] 2016-05-04 08:40
You shouldn't need to care about any dependency. The Node.js headers that downloads using 'make targets' contains all dependencies so it can be compiled on any system - you just need to have a compiler installed.

**Comment by lpinca** [comment] 2016-05-04 08:45
```bash
luigi@macbook:uWebSockets (master)$ make
Scanning dependencies of target uWS
[ 16%] Building CXX object CMakeFiles/uWS.dir/src/uWS.cpp.o
/Users/luigi/Desktop/repos/uWebSockets/src/uWS.cpp:46:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/uWS.dir/src/uWS.cpp.o] Error 1
make[1]: *** [CMakeFiles/uWS.dir/all] Error 2
make: *** [all] Error 2
```

unless I do `brew link --force openssl`.

**Comment by alexhultman** [comment] 2016-05-04 08:47
When building the project for Node.js you only need to cd into nodejs and build in that folder. The CMake project in the root folder only builds native stuff. This could be documented better.

**Comment by lpinca** [comment] 2016-05-04 08:52
This commit https://github.com/alexhultman/uWebSockets/commit/8af32c13145f3e738490a84f307cf39b4b00e89c simplified things quite a bit :)

**Comment by alexhultman** [comment] 2016-05-04 08:57
Yep and if you look at .travis.yml you can see how it compiles without setting up anything extra. I should probably add documentation for this.

**Comment by lpinca** [comment] 2016-05-04 09:02
Yeah, I tried, and it works fine. It should be definitely documented. README compilation instructions make you assume that that step is required.
