### ISSUE TITLE
Segmentation fault when running tests

### ISSUE THREAD

**Issue by alexhultman** [alexhultman/uWebSockets#44] opened 2016-04-10 18:04 UTC
I just noticed it can segfault sometimes when I run the primus tests. I guess it has to do with closing the server, but I do not know for sure yet. I should fix this up.

**Comment by lpinca** [comment] 2016-04-10 18:06
Yeah there are some glitches. Sometimes it crashes, other times it hangs. See https://github.com/primus/primus/pull/454.

**Comment by alexhultman** [comment] 2016-04-10 18:08
Yep this will be fixed up quite soon I'll look at this tomorrow.

**Comment by alexhultman** [comment] 2016-04-11 06:22
The problem is that the primus tests are both closing every opened socket (socket.close), but also closing the server (server.close). Closing the server will close all sockets so I just need to add some check to not double close a socket.

**Comment by alexhultman** [comment] 2016-04-11 06:42
For me it seems to crash in all sorts of ways on the test "can be opened and closed". Sometimes it crashes later but 90% is at that test.

**Comment by alexhultman** [comment] 2016-04-11 06:47
No no, its the one prior, the "should set the correct read/writable states".

**Comment by lpinca** [comment] 2016-04-11 06:52
I can't reproduce the issue on OS X.

**Comment by alexhultman** [comment] 2016-04-11 06:54
There is a problem though.

```javascript
for (var i = 0; i < 100; i++) {

      it('should set the correct read/writable states', function (done) {
        var socket = new Socket(server.addr);

        expect(socket.readable).to.equal(true);
        expect(socket.writable).to.equal(true);

        socket.once('open', function () {
          expect(socket.readable).to.equal(true);
          expect(socket.writable).to.equal(true);

          socket.once('end', function () {

            expect(socket.readable).to.equal(false);
            expect(socket.writable).to.equal(false);

            socket.once('open', function () {
              expect(socket.readable).to.equal(true);
              expect(socket.writable).to.equal(true);

              socket.once('end', done).end();
            }).open();
          }).end();
        });
      });

}
```

What kinds of native calls can I expect from this test? Is is closing multiple times? I get all kinds of crashes from this test.

**Comment by lpinca** [comment] 2016-04-11 06:58
Every `end()` call closes the WebSocket connection and every `open()` call creates a new one.

**Comment by alexhultman** [comment] 2016-04-11 07:04
Well I should probably just write a test that makes a million disconnections/connections then. I thought I had that thing nailed...

**Comment by lpinca** [comment] 2016-04-11 07:39
I wonder if it is a race condition between the client closing a socket and the server being closed closing the same socket.

**Comment by alexhultman** [comment] 2016-04-11 07:45
I thought so at first but then I looked at the code and when a socket is closed, it removes itself from the servers list of sockets so it cannot close the same. But this is no problem, I'll just have to track this down.

**Comment by alexhultman** [comment] 2016-04-11 07:50
Both of the TravisCI tests failed at the same test that I fail at here. So that's good news at least.

**Comment by alexhultman** [comment] 2016-04-11 08:54
Well I just put a bunch of prints at the top of all functions and this is what I get:

```
Server init, no port: 0
      ✓ exposes a compatible socket
Server close: 0
Server init, no port: 0
Socket close: 0x1ae5fd0
Socket close: 0x1ae5fd0
      ✓ should set the correct read/writable states
Socket close: 0x1adb5a0
Socket send: 0x1ae5fd0
Segmentation fault (core dumped)
```

So it does seem that the test is really hammering on all kinds of buttons it can. It obviously calls functions that ends up closing the same socket twice, even sending on a closed socket.

**Comment by alexhultman** [comment] 2016-04-12 04:42
I have found the problem. This was a very strange thing to debug. I forgot to clone the socket object passed to onConnection, so i just passed a reference to a shared socket that later on went overwritten so it got messed up at a later stage. This is something I already solved in node-lws but apparently forgot about.

**Closed** 2016-04-12 04:49 UTC
Labels: bug

**Comment by lpinca** [comment] 2016-04-12 05:42
Awesome.
