### ISSUE TITLE
Pass Engine.IO tests

### ISSUE THREAD

**Issue by suhaotian** [alexhultman/uWebSockets#65] opened 2016-04-22 15:03 UTC
👍

**Comment by alexhultman** [comment] 2016-04-22 15:44
The long term goal is to either replace or expose an alternative to ws in all the major "real-time frameworks" <- this name is ridiculous. Socket.IO, SocketCluster, Primus, etc. This is up to the developers of each of these projects though, I cannot force myself on anyone.

**Comment by LordMajestros** [comment] 2016-04-22 18:00
I did a port of engine.io to las a while back. I just pushed it here https://github.com/LordMajestros/engine.io.lws maybe I could try this.

**Comment by LordMajestros** [comment] 2016-04-22 18:01
@alexhultman You're still planning to support SSL right?

**Comment by alexhultman** [comment] 2016-04-22 18:03
I'm currently playing around with SSL transfer.

**Comment by alexhultman** [comment] 2016-04-23 08:25
There is already an issue in Engine.IO's tracker, I'm closing this one.

**Comment by LordMajestros** [comment] 2016-04-23 08:46
Port of engine.io to uWebsockets https://github.com/LordMajestros/engine.io.uws

**Comment by alexhultman** [comment] 2016-04-24 06:01
@LordMajestros How do you run the Engine.IO tests? Which ones are failing, and how did you replace ws?

**Comment by LordMajestros** [comment] 2016-04-24 07:40
You use
`npm test`

it currently throws the `Error: registering more than one listener to websocket`
it seems engine.io adds more than one listener to a socket.

**Comment by LordMajestros** [comment] 2016-04-24 09:45
Currently failing on `server messages should arrive from server to client (multiple, ws):` because the socket class in uws does not take a callback as the last argument.

**Comment by alexhultman** [comment] 2016-04-24 10:28
Did you change the Socket to a real EventEmitter?

**Comment by LordMajestros** [comment] 2016-04-24 10:38
No, I did not.
It currently passes that test with the changes in this PR https://github.com/alexhultman/uWebSockets/pull/70.

**Comment by LordMajestros** [comment] 2016-04-24 10:38
It's passing all tests except the ssl tests I haven't tried those yet.

**Comment by alexhultman** [comment] 2016-05-03 22:02
@LordMajestros With v0.3.1 you should be able to pass every test, right?

**Comment by kapouer** [comment] 2016-05-04 00:52
The changes in @LordMajestros [engine.io fork](https://github.com/LordMajestros/engine.io.uws) are encouraging but difficult to follow.
I tried with only completely trivial changes, on a [clean fork](https://github.com/kapouer/engine.io/tree/uws), all tests pass except 8 failures (over 107) in `mocha test/server.js`:
- 3 failed graceful closes, i think you're already addressing this in master
- 5 IntXXArray, Buffer, ArrayBuffer binary data tests

**Comment by alexhultman** [comment] 2016-05-04 11:27
@kapouer We should implement the removeListener function in uws.js if engine.io uses it.

**Comment by kapouer** [comment] 2016-05-04 13:07
@alexhultman could Socket extends EventEmitter as well - event if it has to override some methods, it'd be a little prettier. Do `throw new Error("EE_ERROR")` lines should better be emitting `error` events on the Socket instance (as an event emitter) ?

**Comment by alexhultman** [comment] 2016-05-04 13:09
Socket was initially an EventEmitter but this phony EventEmitter performs a lot better in memory usage and performance.

**Comment by kapouer** [comment] 2016-05-04 13:13
ok, i won't question that affirmation ;) The question now is if engine.io actually depend on that `error` event listener to be truely emitting errors or not, then ?

**Comment by alexhultman** [comment] 2016-05-04 15:54
Ah, the EE_ERROR is not meant to be part of the interface. It should never throw, but if it does (you register more than one listener to a socket) it fails.

**Comment by alexhultman** [comment] 2016-05-04 16:10
@kapouer You should now be able to use removeListener as of v0.3.2

**Comment by alexhultman** [comment] 2016-05-04 20:59
The fails regarding binary data sending is because ws automatically sets opcode to binary when passing anything not string to send. Fixing this leaves 3 fails from graceful server closing.

**Comment by kapouer** [comment] 2016-05-05 09:33
With your fixes and this [trivial engine.io PR](https://github.com/socketio/engine.io/pull/390) you can simply run the engine.io tests using `eio_ws_module=uws mocha test/server.js`.

**Comment by LordMajestros** [comment] 2016-05-05 11:57
@kapouer How are you running the tests? I'm using nom tests and only 4 tests pass

**Comment by kapouer** [comment] 2016-05-05 12:03
I'm using https://github.com/alexhultman/uWebSockets/pull/88 and in "uwebsocket/nodejs/" dir i do
```
make dist
cd dist
npm link
```

Then in my engine.io repository i do
```
npm install
npm link uws
eio_ws_module=uws mocha test/server.js
```

**Comment by alexhultman** [comment] 2016-05-06 15:37
The last 3 issues are because engine.close() does not actually call wss.close(), yet they expect the process to exit.

**Comment by kapouer** [comment] 2016-05-06 16:05
Hey, try to do:
``` node test/fixtures/server-close.js ```
it exits cleanly.
Something is happening with "exec".

**Comment by alexhultman** [comment] 2016-05-06 18:58
Yeah exactly, it doesn't exit and that is the cause of failure. This should be easy to fix I just need to investigate the exact behavior of ws because this behavior seems quite undocumented. I need to clean up things from the event-loop to allow Node.js to quit but they never call my close() function.

**Comment by kapouer** [comment] 2016-05-06 19:41
If i do
`EIO_SERVER_WS_MODULE=uws node test/fixtures/server-close.js`
with
```
var eioc = require('engine.io-client');
var listen = require('../common').listen;
var engine = listen(function (port) {
  var socket = new eioc.Socket('ws://localhost:' + port);
  socket.on('open', function() {
    engine.httpServer.close();
    engine.close();
    engine.ws.nativeServer.close();
  });
});
```
it exits, other it hangs.

**Comment by alexhultman** [comment] 2016-05-06 19:49
If you comment out lines 209 to 249 in uWS.cpp all tests pass. I need to remove these when running as a Node.js addon.

**Comment by kapouer** [comment] 2016-05-06 19:53
Makes sense... you have to garbage-collect your uv loop somehow.
Otherwise https://github.com/kapouer/engine.io/commit/3acbdc0f89249a0d28bd56450da388e1ecd9e6c0 explicitely has to do it.

**Comment by alexhultman** [comment] 2016-05-06 19:54
No the loop is owned by Node.js, I just need to not add anything extra to it because as long as you have anything registered in it it will not return and exit.

**Comment by kapouer** [comment] 2016-05-06 19:56
Depends how you see it, but yes you don't need two loops - figure i [already know things like that](https://github.com/kapouer/node-webkitgtk/blob/master/src/webview.cc#L194) but it's in a simpler case.

**Comment by alexhultman** [comment] 2016-05-06 20:10
Sure there are two solutions to this: either fix engine.io (they should really not depend on this very particular and undocumented behavior of ws) or "fix" µWS by not registering anything other than the sockets to the loop. I find it very bad coding to rely on onducumented behavior like this and not simply call close() on the ws server. But I'm sure they will say that this is a flaw in µWS and nothing to do with engine.io.

**Comment by kapouer** [comment] 2016-05-06 20:34
It's worth a shot, let me PR that just in case

**Comment by alexhultman** [comment] 2016-05-06 20:50
I have this solved here now. Just doing some testing.

**Closed** 2016-05-06 21:17 UTC
Labels: high priority
