### ISSUE TITLE
Support for the "path" option in Server's constructor

### ISSUE THREAD

**Issue by ide** [alexhultman/uWebSockets#46] opened 2016-04-11 20:15 UTC
I was looking into switching from ws to uws for react-native's devtool infrastructure but all the existing call sites pass the "path" option into the ws.Server constructor. Wanted to point this out in case current users of ws are part of your intended audience.

**Comment by alexhultman** [comment] 2016-04-12 03:15
I will support path in the upcoming releases.

**Comment by alexhultman** [comment] 2016-04-12 11:13
The idea behind having the `ws` interface is to allow easy switching from current code bases to µWS and back. The goal is to support as much as possible to make the switch easy but also to allow switching back to ws in cases where µWS miss functionality. So this feature will be added but if you stumble on new issues you should be able to switch back very easily.

**Comment by ronkorving** [comment] 2016-04-12 15:52
Honestly, this has the potential to be way bigger than ws. Nobody will care about the ws API.

**Comment by alexhultman** [comment] 2016-04-12 20:04
@ide What is react-native and how does it contain ws? In what way will it be used? What module makes use of WebSockets?

**Comment by ide** [comment] 2016-04-12 21:17
@alexhultman it's a project for making apps and is getting popular: https://github.com/facebook/react-native. It comes with some development tools that run on Node and use WebSockets to communicate with your phone and your browser. High performance or memory usage isn't important because this is a developer tool with a small number of connections, but I liked that uws has no dependencies, installs more quickly than "ws", and you are more actively working on it.

The features of "ws" that react-native uses are:
- Server:
  - the `path` option in the Server constructor
  - "connection", "error", and "close" events
    - it also uses the `onmessage`, `onerror`, and `onclose` properties, but we could change the code to use the EventEmitter API instead
- Connected client (received from `wss.on('connection', (ws) => ...)`):
  - `ws.upgradeReq.url`
  - `ws.send(...)` and `ws.close()` methods

These are the places in the code that use "ws":
https://github.com/facebook/react-native/blob/master/local-cli/server/util/webSocketProxy.js#L13
https://github.com/facebook/react-native/blob/master/local-cli/server/util/messageSocket.js#L13
https://github.com/facebook/react-native/blob/master/local-cli/server/util/attachHMRServer.js#L109

**Comment by alexhultman** [comment] 2016-04-13 11:11
066bc9f244faf7a91d595f0ce924877e8e6b6c10

This adds support for basic "path" rejection. I'm not 100% sure about the usage but currently it simply rejects all connections that do not match the set path. If you set server path to "/some_path" it will only accept connections with GET /some_path. This is pretty useless currently, I guess the usage is to allow multiple paths on the same server and route the callbacks accordingly. How are you using it?

**Comment by alexhultman** [comment] 2016-04-13 11:15
Ah okay I see how you use it. I need to support taking a HTTP server as option and then register listeners to that servers 'upgrade' event.

**Comment by LordMajestros** [comment] 2016-04-13 11:24
Most servers use only one path from what I've seen. This helps when using nginx as a load balancer or proxy. The upgrade option is only needed on that path.

**Comment by alexhultman** [comment] 2016-04-13 12:06
20648708a6728f5dd663faa8e69ccba4226b84ac

This is now supported but I do not know if I should close the connection when the path doesn't match. Currently I close it, so you can only have 1 path per httpServer (the first that doesn't match will close it, so the next WebSocket server in the chain will not get a chance to accept the connection).

**Comment by LordMajestros** [comment] 2016-04-13 12:16
I think it should be closed as soon as possible if it doesn't match. That reduces the possibility of some type of attack on the server.
If you want another path you can run a server on another port and load balance with nginx while exposing the same port to the outside world using nginx and the second path. 
I really haven't seen a use case for multiple websocket paths on one server.
Different logic for different websocket functions can be coded in based on authentication using cookies, JSON web tokens, etc.

**Comment by alexhultman** [comment] 2016-04-13 12:21
@ide if you use onmessage, onclose, etc (I did not know ws had these) then we should support these as well.

**Comment by LordMajestros** [comment] 2016-04-13 12:33
@alexhultman I'm going to attempt to convert a project that uses ws as the backend I would really appreciate those (onmessage, onclose)

**Comment by alexhultman** [comment] 2016-04-13 12:34
Anyone who has a ws project is free to just try and swap and report all problems.

**Comment by alexhultman** [comment] 2016-04-13 12:50
Okay I published v0.2.2. This should address all issues, but there might be some initial problems.

**Comment by ide** [comment] 2016-04-14 19:15
Thanks!

**Comment by alexhultman** [comment] 2016-04-14 19:19
Did it work? I'm eager to hear any new issues so that I can fix up the ws interface and fix any differences from the original.

**Comment by ide** [comment] 2016-04-14 20:20
I upgraded uws and encountered `TypeError: Cannot read property 'onmessage' of undefined` from line 144 of uws.js. From what I can tell, `nativeServer.onMessage` is getting called before `nativeServer.onConnection`.

**Comment by alexhultman** [comment] 2016-04-14 20:25
Are you on OS X?

**Comment by ide** [comment] 2016-04-14 20:25
Yeah OS X 10.11.4 with Node 5.10.0.

**Comment by alexhultman** [comment] 2016-04-14 20:26
Then I would say there is a 105% chance of me forgetting to update the OS X build. I really need to get this Travis thing up.

**Comment by alexhultman** [comment] 2016-04-14 20:28
There are 2 onConnections: one at line 131 and one at 181. When using the path & server options you will get the one at 181.

**Comment by ide** [comment] 2016-04-14 20:30
OK yeah. The onConnection at 181 is getting called before onMessage as expected.

**Comment by alexhultman** [comment] 2016-04-14 20:32
Yep then I need to publish some new OS X builds, will be up in a short while, I just need to check my history to see that this really is the case (I'm pretty sure it is).

**Comment by alexhultman** [comment] 2016-04-14 20:53
Yep, I did an invalid assumption that nothing had changed. Now I have published updated builds that should work, at least to some degree :P

**Comment by ide** [comment] 2016-04-14 21:00
Thanks for the update. Made a little more progress but am now seeing `Assertion failed: (val->IsUint8Array()), function Data, file ../src/node_buffer.cc, line 194.` It's probably this line here: https://github.com/nodejs/node/blob/master/src/node_buffer.cc#L184, haven't investigated further than that though.

**Comment by alexhultman** [comment] 2016-04-14 21:08
The problem is probably what types you pass to send. Currently it only accepts String or Node.js buffer but it seems the ws module can also send other types. I think the most effective thing you could do is to just add hacks into the uws.js to make sure that the send function only gets a Node.js buffer or a String. Then when you have something working I can look at this and integrate it into the module in some way. I think that is the best for both of us.

**Comment by alexhultman** [comment] 2016-04-18 21:35
The upcoming version has support for sending any type (String, Buffer, TypedArray) and support for close(code, data). @ide did you mnage to get things working?

**Comment by ide** [comment] 2016-04-18 21:46
No I haven't gotten around to trying things since then.

**Comment by alexhultman** [comment] 2016-04-18 21:51
Okay but just wait for the next release then, it should be a lot more feature-complete. I'll close this issue since it is part of next release and already solved. The issue we are talking about is #61 which is also closed.

**Closed by alexhultman** 2016-04-18 21:51 UTC
Labels: enhancement

**Comment by alexhultman** [comment] 2016-04-18 23:42
I pushed a new version now.
