### ISSUE TITLE
Clean up on server.close(), don't close socket on non-matching path

### ISSUE THREAD

**Issue by 131** [alexhultman/uWebSockets#120] opened 2016-05-20 16:04 UTC
I tried to switch from ws to uws and i encounter the same bug (fixed in https://github.com/websockets/ws/commit/ffed6ef03c3eb530d0cf9836a5fc5758037fc8c7)

Reproduce
* A long running http server
* An dedicated uws instance plugged on it {server: originalserver, path : /}
* a /livestream uws intance registered on  {server: originalserver, path : /livestream}
* i disconnect /livestream uws (instance.close())
* re-create livestream instance
* Start a WS client en /livestream 
* => crash

new uws.Server().close() is far too simple (it should at least detach upgrade handlers when attaching an existing http server)

https://github.com/alexhultman/uWebSockets/blob/master/nodejs/dist/uws.js#L320

**Comment by alexhultman** [comment] 2016-05-20 16:08
Thanks for this report, I will be checking into this in a while.

**Comment by 131** [comment] 2016-05-20 16:28
See https://github.com/alexhultman/uWebSockets/pull/121

**Comment by alexhultman** [comment] 2016-05-24 11:23
So, this issue is about two things?

1. Don't close the socket if the path is not matching?
2. Clean up stuff on WebSocketServer.close()?

**Comment by 131** [comment] 2016-05-24 13:10
That's it

**Comment by alexhultman** [comment] 2016-05-24 13:23
Can you describe the behavior you want in words, how does it prevent a build-up of sockets that just wants to be closed? What is the behavior of ws?

**Comment by alexhultman** [comment] 2016-05-24 13:24
The only sane behavior I can think of is some haxxy solution like this:

* Get called on the 'upgrade' event
* Try and determine your place in the calling chain
* If not matching path AND last in chain THEN close

**Comment by 131** [comment] 2016-05-24 14:19
ws do not bother much. WHEN registered with a path, IF the path do not match, it return (without closing the socket).

see https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js#L160

**Comment by alexhultman** [comment] 2016-05-24 14:27
So if you connect 1 million connections to ws on a path that is not used, it will leak sockets? Well, I will solve this by listening to 'upgrade' 'newListener' and 'removeListener' events and determine if we are last in the chain based on this.

**Comment by 131** [comment] 2016-05-24 14:31
I'll PR in ws with your work once it's donce then :smile:

**Comment by 131** [comment] 2016-05-24 15:55
More seriously, i think you'll be solving an issue that is not uws' (and i'm afraid of side effects). 


For the user perspective, i think you can state : if you'd like to register a uws handler to an existing server with a path, make sure to also register ANOTHER uws handler on the global scheme (i.e. with no path) that will just drop sockets, if there is nothing else here to do.

You can also force the upgrade event to be handled synchronously and close it if that is not the case

```
on('upgrade' //
process.nextTick(function(){
  if(!socket.handled)
    socket.close();
})
```

All solutions that involve going outside this library scope have downsides.

**Comment by alexhultman** [comment] 2016-05-24 16:11
It's not hard to solve reliably, I would rather solve it reliably than rely on users knowing internal details. All you need is to register to the 'newListener' and 'removeListener' events and store the other listeners in a map. When the map is empty, boolean isLastInUpgradeChain = true, when it is not empty, boolean isLastInUpgradeChain = false. Then we just check this boolean to determine if we are going to close the socket or not.

By using this nextTick solution you are not guaranteed to get the correct behavior, in fact it will not work at all when having two paths registered, you will only push the problem to the next iteration.

**Comment by alexhultman** [comment] 2016-05-31 12:01
@131 I just tested and commited an example that registers two different servers on two different paths - one echo server and one upper case echo server. It works, there is no issue with closing the socket so I don't see how this could be an issue.

https://github.com/alexhultman/uWebSockets/blob/master/nodejs/paths.js

**Comment by alexhultman** [comment] 2016-05-31 12:04
Since it works pretty elegant already (it makes sure to never leave a socket open when it shouldn't, yet it works with multiple paths), I think the only issue is to fix the server.close() issue, right?

**Comment by alexhultman** [comment] 2016-05-31 12:09
@131 Could you modify the paths.js example to reproduce your crash issue? It should be very simple as it already does most of what you describe.

**Comment by alexhultman** [comment] 2016-05-31 19:14
I reproduced a crash that is now fixed. I guess this should fix all your issues.

**Closed by alexhultman** 2016-05-31 19:14 UTC
Labels: enhancement, high priority
